### ISSUE TITLE
Inquiry into ippe_py

### ISSUE THREAD

**Issue by yorklyb** [royxue/ippe_py#3]
Hi Roy,

I'm doing research on fiducial marker-based navigation:
https://www.youtube.com/watch?v=3jVkphKte30

However, when the camera is more than 2 meters away from the tag, the pose estimation becomes very unstable. Then I employed the Kalman-filter and low pass filter but the result was still not promising.
 
I checked the history of the 2D image points and found that they were stable since I was using Apriltags. So I think the main source of the unstable estimation is the PnP method itself. And my case is similar to the following demo:
https://www.youtube.com/watch?v=Efb0zux-_hU

So I hope that I can use the IPPE instead of the default iterative method and I looked into this package.

I’m using python 3.6.9+ Opencv 4.4.1 where cv2.solvepnp() doesn’t have the flag of SOLVEPNP_IPPE.  I apologize that this might be a stupid question but I’m wondering is there any demo available that can teach me how to use some function like the solveGeneric in the C++ implementation. And I’m also wondering if Opencv 4.4.1 works for the package. 
 
I really appreciate any help

**Comment by royxue** [comment]
Hi, this IPPE was original developed for python2.7 environment, I think it might have some conflicts towards python3.6+ and latest version of opencv, numpy, I could spend some time this weekend, update it to py3 version

**Comment by yorklyb** [comment]
Thank you so so much. I feel like the IPPE is available in solvePnPGeneric because I can find an attribute called cv2.SOLVEPNP_IPPE, but I don't know how to use it. Here is what I tried: 
```Python
import numpy as np
import cv2
import cv2.cv2 as cv



points_3d = np.array(([-8.6, 8.6, 0],
                  [8.6, 8.6, 0],
                  [8.6, 8.6, 0],
                  [-8.6, 8.6, 0]),
                 dtype=np.double)

points_2d = np.array(([354,114],
 [454,106],
 [467,202],
 [353,206]),dtype=np.double)

cam1_matrix = np.array(([330.6,0,326.8336],[0,330.6,251.8424],[0,0,1]),dtype=np.double)

dist_coefs1 = np.array([-0.302587121740377,0.068024115878877,0.001645011282553,0.002976587367681,0],dtype=np.double)

# found, rvec, tvec = cv2.solvePnP(points_3d, points_2d, cam1_matrix, dist_coefs1)
# print(rvec, tvec)
# found, rvec, tvec = cv.solveP3P(points_3d, points_2d, cam1_matrix, dist_coefs1,5,rvecs = None,tvecs =None)
# print(rvec[0], tvec[0])

found, rvec, tvec = cv.solvePnPGeneric(points_3d, points_2d, cam1_matrix, dist_coefs1,rvecs = None,tvecs =None, useExtrinsicGuess=None,flags=6,rvec = None,tvec =None,reprojectionError=None)
print(rvec, tvec)
```
Sorry to pull this request but all the tutorials I can find is about the default method, something like found, rvec, tvec = cv2.solvePnP(points_3d, points_2d, cam1_matrix, dist_coefs1).

**Comment by royxue** [comment]
did you tried with C++ version of opencv?

**Comment by yorklyb** [comment]
Hi, I found the following codes worked. I will close the issue now. Thanks!
```
found, rvec4, T0, repro = cv2.solvePnPGeneric(points_3d, points_2d, cam1_matrix, dist_coefs1, rvecs = None, tvecs = None, useExtrinsicGuess= None,flags = cv2.SOLVEPNP_IPPE_SQUARE ,
                    rvec= None, tvec = None,reprojectionError= 3)
```
